---
title: "Bin abundance"
author: "Stephen Noell"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      fig.align = "center",
                      fig.width = 10,
                      fig.height = 6)
```


```{r Libraries and seed}

# Libraries
library("tidyverse")       # data wrangling and visualisation
library("patchwork")       # plots together
library("viridis") #color package
library("svglite") #for saving SVGs
library("ggpubr") #for saving plots
library("here")            # set the path to the folder 
library("RColorBrewer")
library(pheatmap)
library(tidyr)
library(ComplexHeatmap)

set.seed(57)
```


```{r Load the data}
# Load data
ba_all <-  read.csv(file = "gtdb_checkm_abund_all4_dedup.csv")

mags.ogt <- read.csv(file = "tome_all5.csv") %>%
  dplyr::select(-Site)

ba_on.0 <-inner_join(ba_all, mags.ogt) %>%
  unite(bin_tax, c("bin", "Domain", "Phylum", "Class", "Order")) %>%
  column_to_rownames(., var = "bin_tax") %>%
  select(., Mel_abundance, Ritt3_abundance, WC_abundance, TR_abundance,
         Mel_presence, Ritt3_presence, TR_presence, WC_presence, predOGT) %>%
  dplyr::rename(Melbourne_1 = Mel_abundance) %>%
  dplyr::rename(Rittmann_1 = Ritt3_abundance) %>%
  dplyr::rename(`Erebus-WC_1` = WC_abundance) %>%
  dplyr::rename(`Erebus-TR_1` = TR_abundance)

#### If a MAG is defined as absent from a site based on containment, mark its abundance as 0
ba_on_pres0 <- ba_on.0 %>%
  mutate(Melbourne = case_when(
      Mel_presence == 0 ~ 0,
      TRUE ~ Melbourne_1)) %>%
  mutate(Rittmann = case_when(
      Ritt3_presence == 0 ~ 0,
      TRUE ~ Rittmann_1)) %>%
  mutate(`Erebus-WC` = case_when(
      WC_presence == 0 ~ 0,
      TRUE ~ `Erebus-WC_1`)) %>%
  mutate(`Erebus-TR` = case_when(
      TR_presence == 0 ~ 0,
      TRUE ~ `Erebus-TR_1`)) %>%
  select(Melbourne, Rittmann, `Erebus-WC`, `Erebus-TR`, predOGT)

ba_ogt <- ba_on_pres0 %>% select(predOGT)

ba_on_pres <- ba_on_pres0 %>%
  select(-predOGT) %>%
  mutate_all(funs(. + 1E-4)) %>%
  mutate_all(., log10)

ba_mat.2 <- as.matrix(ba_on_pres)
ba_mat.3 <- as.matrix(ba_ogt)

pheatmap(ba_mat.2,
        color = colorRampPalette(brewer.pal(8, "Reds"))(25),
        height = 15, 
        width = 9,
        fontsize_col = 10,
        fontsize_row = 8)


hmap <- Heatmap(ba_mat.2,
        col = colorRampPalette(brewer.pal(8, "Reds"))(25),
        heatmap_legend_param = list(legend_direction = "horizontal", 
                                      legend_width = unit(5, "cm"))) + 
  Heatmap(ba_mat.3,
          col = colorRampPalette(brewer.pal(8, "Reds"))(25),
          heatmap_legend_param = list(legend_direction = "horizontal", 
                                      legend_width = unit(5, "cm")))

draw(hmap, heatmap_legend_side = "bottom")

```
